# -*- coding: utf-8 -*-
"""Data Mining Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/150tQs92s9alLkvPJiKUyMBXAgYatn2-f

# PENGELOMPOKAN PROVINSI DI INDONESIA BERDASARKAN ANGKA PARTISIPASI MURNI PENDIDIKAN MENGGUNAKAN ALGORITMA K-MEANS

## 1. Business Understanding

**Problem:**
Indonesia, a vast archipelago, exhibits significant disparities in educational access and participation across its provinces. Understanding these variations is crucial for targeted policy interventions and resource allocation.

**Objective:**
To cluster Indonesian provinces based on their 'Angka Partisipasi Murni (APM)' (Pure Participation Rate) across different educational levels. This clustering will help identify groups of provinces with similar educational participation patterns, allowing for more effective and localized policy development to improve educational equity and access.

## 2. Data Understanding

First, let's load the provided Excel file and inspect its structure.
"""

import pandas as pd

# Load the Excel file
file_path = '/content/Angka Partisipasi Murni (APM) Menurut Provinsi dan Jenjang Pendidikan, 2025.xlsx'
df = pd.read_excel(file_path)

# Display the first 5 rows of the DataFrame
display(df.head())

# Display basic information about the DataFrame, including data types and non-null values
df.info()

# Display descriptive statistics for the numerical columns
display(df.describe())

"""### Summary of Data Understanding:

*   The dataset contains 38 entries, each representing a province in Indonesia.
*   There are 4 columns: '38 Provinsi', 'SD/sederajat', 'SMP/sederajat', and 'SMA/sederajat'.
*   All numerical columns ('SD/sederajat', 'SMP/sederajat', 'SMA/sederajat') are of float64 type and have no missing values, as indicated by the `df.info()` output.
*   Descriptive statistics reveal a higher mean participation rate for lower education levels (SD/sederajat) which gradually decreases for higher levels (SMP/sederajat, SMA/sederajat).
*   There is a significant range in participation rates, particularly for SMA/sederajat, suggesting variability across provinces which K-Means clustering can help to identify.

## 3. Data Preparation

This phase involves cleaning and transforming the data to make it suitable for the K-Means algorithm. We will begin by renaming columns for better readability.
"""

# Rename columns for clarity
df.rename(columns={
    '38 Provinsi': 'Provinsi',
    'SD/sederajat': 'APM_SD',
    'SMP/sederajat': 'APM_SMP',
    'SMA/sederajat': 'APM_SMA'
}, inplace=True)

# Display the first few rows with new column names
display(df.head())

"""### Cek duplikat dan missing Value"""

# Check for duplicate rows
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

# Check for missing values
missing_values = df.isnull().sum()
print("\nMissing values per column:")
print(missing_values)

"""### Feature Selection and Scaling

For K-Means clustering, we need to select the numerical features that represent the characteristics we want to cluster by. In this case, these are the APM values for different education levels. It's also crucial to scale these features because K-Means is a distance-based algorithm, and features with larger values might disproportionately influence the distance calculations.

We will use `StandardScaler` to standardize the features (mean=0, variance=1).
"""

from sklearn.preprocessing import StandardScaler

# Select the features for clustering
X = df[['APM_SD', 'APM_SMP', 'APM_SMA']]

# Initialize the StandardScaler
scaler = StandardScaler()

# Scale the features
X_scaled = scaler.fit_transform(X)

# Convert the scaled features back to a DataFrame for better readability
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

# Display the first few rows of the scaled data
display(X_scaled_df.head())

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize the distribution of scaled features
plt.figure(figsize=(15, 5))
for i, column in enumerate(X_scaled_df.columns):
    plt.subplot(1, 3, i + 1)
    sns.histplot(X_scaled_df[column], kde=True)
    plt.title(f'Distribution of {column} (Scaled)')
    plt.xlabel('Scaled Value')
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

"""## 4. Modeling

In this phase, we will apply the K-Means clustering algorithm to group the provinces based on their educational participation rates. The first step is to determine the optimal number of clusters (k).

### Elbow Method to Determine Optimal k

The Elbow Method is a heuristic used to determine the number of clusters in a dataset. The idea is to run K-Means clustering for a range of k values (e.g., from 1 to 10) and calculate the sum of squared distances from each point to its assigned center (inertia). The plot of inertia against the number of clusters should resemble an arm, and the 'elbow' (the point of inflection) on the curve indicates the optimal k.
"""

from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings('ignore') # Suppress KMeans convergence warnings

# Calculate inertia for different numbers of clusters
inertia = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10) # Added n_init to suppress warning
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

# Plot the Elbow Method graph
plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), inertia, marker='o', linestyle='--')
plt.title('Elbow Method for Optimal K')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia (Within-cluster sum of squares)')
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

"""### Applying K-Means Clustering

Based on the Elbow Method, we will choose `k=3` as the optimal number of clusters. We will now apply the K-Means algorithm with this chosen k and assign the cluster labels back to our original DataFrame.
"""

# Initialize KMeans with the optimal number of clusters (k=3)
k_optimal = 3
kmeans_model = KMeans(n_clusters=k_optimal, random_state=42, n_init=10)

# Fit KMeans to the scaled data and predict clusters
df['Cluster'] = kmeans_model.fit_predict(X_scaled)

# Display the first few rows with the assigned clusters
display(df.head())

"""### Cluster Analysis

Now that the provinces have been assigned to clusters, we need to analyze the characteristics of each cluster to understand what differentiates them. We will calculate the mean `APM_SD`, `APM_SMP`, and `APM_SMA` for each cluster and count the number of provinces in each cluster.
"""

# Calculate the mean of APM values for each cluster
cluster_means = df.groupby('Cluster')[['APM_SD', 'APM_SMP', 'APM_SMA']].mean()
display(cluster_means)

# Count the number of provinces in each cluster
cluster_counts = df['Cluster'].value_counts().sort_index()
print("\nNumber of provinces per cluster:")
display(cluster_counts)

"""#### Interpretation of Clusters:

Based on the `cluster_means`:

*   **Cluster 0 (19 Provinces):** Provinces in this cluster exhibit generally **high** APM across all educational levels (SD, SMP, SMA). These are likely the regions with well-developed educational infrastructure and high student participation.
*   **Cluster 1 (3 Provinces):** This cluster shows **significantly low** APM across all educational levels. These provinces might face substantial challenges in educational access and retention.
*   **Cluster 2 (16 Provinces):** Provinces in this cluster have **moderate** APM. Their participation rates are lower than Cluster 0 but considerably higher than Cluster 1, indicating an average level of educational participation.

### Cluster Visualization

To better understand the separation and characteristics of these clusters, let's visualize them. Since we have three features, a 3D scatter plot would be ideal to represent the clusters.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a 2D scatter plot of the clusters
plt.figure(figsize=(10, 8))

# Define a palette for the clusters
# Using the existing 'colors' list for consistency, or a seaborn palette
colors_palette = ['red', 'green', 'blue'] # Assuming 3 clusters

sns.scatterplot(
    data=df,
    x='APM_SD',
    y='APM_SMP',
    hue='Cluster',
    palette=colors_palette,
    s=100, # Marker size
    alpha=0.7,
    edgecolor='w' # White edge for better distinction
)

plt.title('2D Cluster Visualization of Provinces by APM (SD vs SMP)')
plt.xlabel('APM_SD')
plt.ylabel('APM_SMP')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Cluster')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Create a 2D scatter plot of the clusters using APM_SMP vs APM_SMA
plt.figure(figsize=(10, 8))

# Use the same palette for consistency
colors_palette = ['red', 'green', 'blue'] # Assuming 3 clusters

sns.scatterplot(
    data=df,
    x='APM_SMP',
    y='APM_SMA',
    hue='Cluster',
    palette=colors_palette,
    s=100, # Marker size
    alpha=0.7,
    edgecolor='w' # White edge for better distinction
)

plt.title('2D Cluster Visualization of Provinces by APM (SMP vs SMA)')
plt.xlabel('APM_SMP')
plt.ylabel('APM_SMA')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Cluster')
plt.tight_layout()
plt.show()

for cluster_num in sorted(df['Cluster'].unique()):
    provinces_in_cluster = df[df['Cluster'] == cluster_num]['Provinsi'].tolist()
    print(f"\nCluster {cluster_num}:")
    for province in provinces_in_cluster:
        print(f"- {province}")

"""## 5. Evaluation

In this phase, we will evaluate the quality of the clustering. While K-Means does not have a 'ground truth' to compare against, we can use intrinsic evaluation metrics to assess how well-separated and compact our clusters are. We will use the Silhouette Score, which measures how similar an object is to its own cluster compared to other clusters.

### Silhouette Score

The Silhouette Score is a measure of how similar an object is to its own cluster (cohesion) compared to other clusters (separation). The silhouette ranges from -1 to +1, where a high value indicates that the object is well matched to its own cluster and poorly matched to neighboring clusters.
"""

from sklearn.metrics import silhouette_score

# Calculate the Silhouette Score for the clustering
silhouette_avg = silhouette_score(X_scaled, df['Cluster'])

print(f"The average Silhouette Score for the clustering is: {silhouette_avg:.2f}")

"""#### Interpretation of Silhouette Score:

A Silhouette Score of **0.46** suggests that the clusters are moderately well-separated. While it's not very close to 1 (indicating highly distinct clusters), it's also far from 0 (indicating overlapping clusters) or negative (indicating incorrect clustering). This score provides reasonable confidence in the quality of the clustering and supports the meaningful differentiation of provinces into the three identified groups.

## 6. Deployment

In this phase, we'll consider how this clustering model could be deployed for practical use. This typically involves saving the trained model and then creating an application interface. For this project, we'll outline how to save the model components (scaler and KMeans model) and then suggest how they could be integrated into a Streamlit application.

### Saving the Model Components

To use the trained model and scaler in a deployment environment (like a Streamlit app), we need to save them. `joblib` is a good choice for this, as it's efficient for large NumPy arrays and objects with a lot of data.
"""

# Install Streamlit library (if not already installed)
!pip install streamlit

import joblib

# Save the scaler
joblib.dump(scaler, 'scaler.pkl')

# Save the KMeans model
joblib.dump(kmeans_model, 'kmeans_model.pkl')

print("Scaler and KMeans model saved successfully as 'scaler.pkl' and 'kmeans_model.pkl'.")

"""### Streamlit Application Outline

A Streamlit application could provide an interactive interface for users to input new province data (APM values) and see which cluster they belong to, or visualize the existing clusters.

Here's a conceptual outline of how a `streamlit_app.py` file would look:
"""

import streamlit as st
import pandas as pd
import joblib

# Load the saved scaler and KMeans model
scaler = joblib.load('scaler.pkl')
kmeans_model = joblib.load('kmeans_model.pkl')

st.title('Pengelompokan Provinsi Berdasarkan APM Pendidikan')
st.write('Aplikasi ini mengelompokkan provinsi berdasarkan Angka Partisipasi Murni (APM) untuk jenjang SD, SMP, dan SMA.')

st.header('Input Data Provinsi Baru')

# User input for APM values
apm_sd = st.number_input('APM SD/sederajat', min_value=0.0, max_value=100.0, value=90.0)
apm_smp = st.number_input('APM SMP/sederajat', min_value=0.0, max_value=100.0, value=70.0)
apm_sma = st.number_input('APM SMA/sederajat', min_value=0.0, max_value=100.0, value=50.0)

if st.button('Prediksi Klaster'):
    # Create a DataFrame from the input
    new_province_data = pd.DataFrame([{
        'APM_SD': apm_sd,
        'APM_SMP': apm_smp,
        'APM_SMA': apm_sma
    }])

    # Scale the input data using the loaded scaler
    scaled_new_province_data = scaler.transform(new_province_data)

    # Predict the cluster
    predicted_cluster = kmeans_model.predict(scaled_new_province_data)[0]

    st.subheader('Hasil Prediksi')
    st.write(f'Provinsi baru ini termasuk dalam **Cluster {predicted_cluster}**.')

    # Optional: Display characteristics of the predicted cluster
    # (This would require loading or re-calculating cluster_means in Streamlit app)
    # For demonstration, let's just indicate based on the interpretation:
    if predicted_cluster == 0:
        st.write('Ini adalah klaster provinsi dengan angka partisipasi murni pendidikan **tinggi**.')
    elif predicted_cluster == 1:
        st.write('Ini adalah klaster provinsi dengan angka partisipasi murni pendidikan **rendah**.')
    else:
        st.write('Ini adalah klaster provinsi dengan angka partisipasi murni pendidikan **moderat**.')

st.subheader('Visualisasi Klaster (Existing Data)')
st.write('Anda juga dapat melihat visualisasi klaster provinsi yang sudah ada di bawah ini.')

# (Further code for visualization using plotly or matplotlib could be added here,
# potentially using the original df with 'Cluster' column and the 'colors' list)
# For example:
# import plotly.express as px
# fig = px.scatter_3d(df, x='APM_SD', y='APM_SMP', z='APM_SMA', color='Cluster',
#                     title='3D Cluster Visualization of Provinces by APM')
# st.plotly_chart(fig)