# -*- coding: utf-8 -*-
"""Data Mining Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/150tQs92s9alLkvPJiKUyMBXAgYatn2-f

# PENGELOMPOKAN PROVINSI DI INDONESIA BERDASARKAN ANGKA PARTISIPASI MURNI PENDIDIKAN MENGGUNAKAN ALGORITMA K-MEANS

## 1. Business Understanding




**Permasalahan**: Indonesia sebagai negara kepulauan yang luas memiliki kesenjangan yang cukup signifikan dalam akses dan partisipasi pendidikan di berbagai provinsi. Memahami perbedaan tersebut sangat penting untuk mendukung penyusunan kebijakan yang tepat sasaran serta alokasi sumber daya yang lebih efektif.

**Tujuan**: Melakukan klasterisasi provinsi-provinsi di Indonesia berdasarkan Angka Partisipasi Murni (APM) pada berbagai jenjang pendidikan. Hasil klasterisasi ini diharapkan dapat mengidentifikasi kelompok provinsi yang memiliki pola partisipasi pendidikan yang serupa, sehingga dapat menjadi dasar dalam perumusan kebijakan pendidikan yang lebih terarah, efektif, dan sesuai dengan karakteristik masing-masing daerah guna meningkatkan pemerataan akses serta kualitas pendidikan.

## 2. Data Understanding
"""

import pandas as pd

# Load the Excel file
file_path = '/content/Angka Partisipasi Murni (APM) Menurut Provinsi dan Jenjang Pendidikan, 2025.xlsx'
df = pd.read_excel(file_path)

# Display the first 5 rows of the DataFrame
display(df.head())

# Infromasi Dataset
df.info()

# Deskriptif Statistic
display(df.describe())

"""### **Ringkasan Data Understanding**

* Dataset yang digunakan terdiri dari 38 baris data, di mana setiap baris merepresentasikan satu provinsi di Indonesia.
* Dataset memiliki 4 atribut, yaitu Provinsi, APM SD/sederajat, APM SMP/sederajat, dan APM SMA/sederajat.
* Seluruh atribut numerik, yaitu SD/sederajat, SMP/sederajat, dan SMA/sederajat, bertipe float64 serta tidak memiliki nilai yang hilang (missing values) berdasarkan hasil pemeriksaan menggunakan df.info(). Kondisi ini menunjukkan bahwa data telah siap digunakan untuk proses analisis tanpa memerlukan penanganan data yang hilang.
* Berdasarkan statistik deskriptif, rata-rata Angka Partisipasi Murni (APM) pada jenjang SD/sederajat merupakan yang tertinggi dibandingkan jenjang pendidikan lainnya. Nilai rata-rata tersebut kemudian menurun pada jenjang SMP/sederajat dan semakin rendah pada jenjang SMA/sederajat. Pola ini mengindikasikan bahwa tingkat partisipasi pendidikan cenderung berkurang seiring meningkatnya jenjang pendidikan.
* Selain itu, terdapat variasi yang cukup besar pada nilai APM antarprovinsi, terutama pada jenjang SMA/sederajat, yang ditunjukkan oleh rentang nilai (range) yang relatif lebar. Variabilitas ini menunjukkan adanya perbedaan tingkat partisipasi pendidikan antarwilayah di Indonesia. Oleh karena itu, penerapan metode K-Means Clustering menjadi relevan untuk mengelompokkan provinsi-provinsi yang memiliki karakteristik partisipasi pendidikan yang serupa, sehingga dapat membantu dalam identifikasi pola serta mendukung penyusunan kebijakan pendidikan yang lebih tepat sasaran.

## 3. Data Preparation

Tahap ini melibatkan proses pembersihan dan transformasi data agar siap digunakan dalam algoritma **K-Means Clustering**. Proses diawali dengan **mengubah nama kolom (renaming columns)** menjadi lebih sederhana dan mudah dipahami. Langkah ini bertujuan untuk meningkatkan keterbacaan data serta mempermudah proses analisis dan pengolahan data pada tahapan selanjutnya. Dengan penamaan kolom yang lebih jelas, proses interpretasi hasil analisis juga menjadi lebih mudah dilakukan.
"""

# Mengubah nama kolom untuk meningkatkan kejelasan dan keterbacaan data
df.rename(columns={
    '38 Provinsi': 'Provinsi',
    'SD/sederajat': 'APM_SD',
    'SMP/sederajat': 'APM_SMP',
    'SMA/sederajat': 'APM_SMA'
}, inplace=True)

# Menampilkan beberapa baris pertama dataset setelah perubahan nama kolom
display(df.head())

"""### Cek duplikat dan missing Value"""

# Cek duplikat
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

# Cek data kosong
missing_values = df.isnull().sum()
print("\nMissing values per column:")
print(missing_values)

"""### Feature Selection and Scaling

Pada proses K-Means Clustering, diperlukan pemilihan fitur numerik yang akan digunakan sebagai dasar pembentukan klaster. Dalam penelitian ini, fitur yang dipilih adalah nilai Angka Partisipasi Murni (APM) pada berbagai jenjang pendidikan, yaitu SD/sederajat, SMP/sederajat, dan SMA/sederajat, karena fitur-fitur tersebut merepresentasikan karakteristik partisipasi pendidikan di setiap provinsi.

Selain pemilihan fitur, proses penskalaan data (scaling) juga sangat penting dilakukan. Hal ini karena algoritma K-Means bekerja berdasarkan perhitungan jarak antar data. Jika terdapat perbedaan skala yang cukup besar antar fitur, maka fitur dengan nilai yang lebih besar dapat memberikan pengaruh yang lebih dominan dalam proses pengelompokan sehingga hasil klaster menjadi kurang optimal.

Untuk mengatasi hal tersebut, digunakan metode StandardScaler yang melakukan standardisasi data dengan mengubah setiap fitur agar memiliki rata-rata (mean) sebesar 0 dan varians (variance) sebesar 1. Dengan demikian, seluruh fitur memiliki skala yang sebanding dan dapat berkontribusi secara proporsional dalam proses pembentukan klaster oleh algoritma K-Means.
"""

from sklearn.preprocessing import StandardScaler

# Select the features for clustering
X = df[['APM_SD', 'APM_SMP', 'APM_SMA']]

# Initialize the StandardScaler
scaler = StandardScaler()

# Scale the features
X_scaled = scaler.fit_transform(X)

# Convert the scaled features back to a DataFrame for better readability
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

# Display the first few rows of the scaled data
display(X_scaled_df.head())

import matplotlib.pyplot as plt
import seaborn as sns

# Visualize the distribution of scaled features
plt.figure(figsize=(15, 5))
for i, column in enumerate(X_scaled_df.columns):
    plt.subplot(1, 3, i + 1)
    sns.histplot(X_scaled_df[column], kde=True)
    plt.title(f'Distribution of {column} (Scaled)')
    plt.xlabel('Scaled Value')
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

"""## 4. Modeling

In this phase, we will apply the K-Means clustering algorithm to group the provinces based on their educational participation rates. The first step is to determine the optimal number of clusters (k).

### Elbow Method to Determine Optimal k

The Elbow Method is a heuristic used to determine the number of clusters in a dataset. The idea is to run K-Means clustering for a range of k values (e.g., from 1 to 10) and calculate the sum of squared distances from each point to its assigned center (inertia). The plot of inertia against the number of clusters should resemble an arm, and the 'elbow' (the point of inflection) on the curve indicates the optimal k.
"""

from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings('ignore') # Suppress KMeans convergence warnings

# Calculate inertia for different numbers of clusters
inertia = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10) # Added n_init to suppress warning
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)

# Plot the Elbow Method graph
plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), inertia, marker='o', linestyle='--')
plt.title('Elbow Method for Optimal K')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('Inertia (Within-cluster sum of squares)')
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

"""### Applying K-Means Clustering

Based on the Elbow Method, we will choose `k=3` as the optimal number of clusters. We will now apply the K-Means algorithm with this chosen k and assign the cluster labels back to our original DataFrame.
"""

# Initialize KMeans with the optimal number of clusters (k=3)
k_optimal = 3
kmeans_model = KMeans(n_clusters=k_optimal, random_state=42, n_init=10)

# Fit KMeans to the scaled data and predict clusters
df['Cluster'] = kmeans_model.fit_predict(X_scaled)

# Display the first few rows with the assigned clusters
display(df.head())

"""### Cluster Analysis

Now that the provinces have been assigned to clusters, we need to analyze the characteristics of each cluster to understand what differentiates them. We will calculate the mean `APM_SD`, `APM_SMP`, and `APM_SMA` for each cluster and count the number of provinces in each cluster.
"""

# Calculate the mean of APM values for each cluster
cluster_means = df.groupby('Cluster')[['APM_SD', 'APM_SMP', 'APM_SMA']].mean()
display(cluster_means)

# Count the number of provinces in each cluster
cluster_counts = df['Cluster'].value_counts().sort_index()
print("\nNumber of provinces per cluster:")
display(cluster_counts)

"""#### Interpretation of Clusters:

Based on the `cluster_means`:

*   **Cluster 0 (19 Provinces):** Provinces in this cluster exhibit generally **high** APM across all educational levels (SD, SMP, SMA). These are likely the regions with well-developed educational infrastructure and high student participation.
*   **Cluster 1 (3 Provinces):** This cluster shows **significantly low** APM across all educational levels. These provinces might face substantial challenges in educational access and retention.
*   **Cluster 2 (16 Provinces):** Provinces in this cluster have **moderate** APM. Their participation rates are lower than Cluster 0 but considerably higher than Cluster 1, indicating an average level of educational participation.

### Cluster Visualization

To better understand the separation and characteristics of these clusters, let's visualize them. Since we have three features, a 3D scatter plot would be ideal to represent the clusters.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a 2D scatter plot of the clusters
plt.figure(figsize=(10, 8))

# Define a palette for the clusters
# Using the existing 'colors' list for consistency, or a seaborn palette
colors_palette = ['red', 'green', 'blue'] # Assuming 3 clusters

sns.scatterplot(
    data=df,
    x='APM_SD',
    y='APM_SMP',
    hue='Cluster',
    palette=colors_palette,
    s=100, # Marker size
    alpha=0.7,
    edgecolor='w' # White edge for better distinction
)

plt.title('2D Cluster Visualization of Provinces by APM (SD vs SMP)')
plt.xlabel('APM_SD')
plt.ylabel('APM_SMP')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Cluster')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# Create a 2D scatter plot of the clusters using APM_SMP vs APM_SMA
plt.figure(figsize=(10, 8))

# Use the same palette for consistency
colors_palette = ['red', 'green', 'blue'] # Assuming 3 clusters

sns.scatterplot(
    data=df,
    x='APM_SMP',
    y='APM_SMA',
    hue='Cluster',
    palette=colors_palette,
    s=100, # Marker size
    alpha=0.7,
    edgecolor='w' # White edge for better distinction
)

plt.title('2D Cluster Visualization of Provinces by APM (SMP vs SMA)')
plt.xlabel('APM_SMP')
plt.ylabel('APM_SMA')
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(title='Cluster')
plt.tight_layout()
plt.show()

for cluster_num in sorted(df['Cluster'].unique()):
    provinces_in_cluster = df[df['Cluster'] == cluster_num]['Provinsi'].tolist()
    print(f"\nCluster {cluster_num}:")
    for province in provinces_in_cluster:
        print(f"- {province}")

"""## 5. Evaluation

In this phase, we will evaluate the quality of the clustering. While K-Means does not have a 'ground truth' to compare against, we can use intrinsic evaluation metrics to assess how well-separated and compact our clusters are. We will use the Silhouette Score, which measures how similar an object is to its own cluster compared to other clusters.

### Silhouette Score

The Silhouette Score is a measure of how similar an object is to its own cluster (cohesion) compared to other clusters (separation). The silhouette ranges from -1 to +1, where a high value indicates that the object is well matched to its own cluster and poorly matched to neighboring clusters.
"""

from sklearn.metrics import silhouette_score

# Calculate the Silhouette Score for the clustering
silhouette_avg = silhouette_score(X_scaled, df['Cluster'])

print(f"The average Silhouette Score for the clustering is: {silhouette_avg:.2f}")

"""#### Interpretation of Silhouette Score:

A Silhouette Score of **0.46** suggests that the clusters are moderately well-separated. While it's not very close to 1 (indicating highly distinct clusters), it's also far from 0 (indicating overlapping clusters) or negative (indicating incorrect clustering). This score provides reasonable confidence in the quality of the clustering and supports the meaningful differentiation of provinces into the three identified groups.

## 6. Deployment

In this phase, we'll consider how this clustering model could be deployed for practical use. This typically involves saving the trained model and then creating an application interface. For this project, we'll outline how to save the model components (scaler and KMeans model) and then suggest how they could be integrated into a Streamlit application.
"""